module.exports = {
    env: {
        es2021: true
    },
    extends: ["eslint:recommended"],
    parserOptions: {
        ecmaVersion: 13,
        sourceType: "module"
    },
    rules: {
        "array-bracket-newline": ["warn", { multiline: true }],
        "array-bracket-spacing": ["warn", "never"],
        "array-element-newline": ["warn", { multiline: true, minItems: 5 }],
        "arrow-body-style": "warn",
        "arrow-spacing": "error",
        "block-spacing": "error",
        "brace-style": ["error", "1tbs"],
        "camelcase": "error",
        "comma-dangle": ["error", "never"],
        "comma-spacing": "error",
        "comma-style": "warn", "eqeqeq": ["error", "smart"],
        "curly": ["warn", "multi-line"],
        "default-param-last": "warn",
        "dot-location": ["warn", "property"],
        "func-call-spacing": "error",
        "function-call-argument-newline": ["warn", "consistent"],
        "function-paren-newline": "warn",
        "indent": ["error", 4],
        "jsx-quotes": "warn",
        "key-spacing": "warn",
        "keyword-spacing": "warn",
        "no-array-constructor": "error",
        "no-duplicate-imports": "error",
        "no-extra-parens": "warn",
        "no-extra-semi": "warn",
        "no-multi-spaces": "error",
        "no-trailing-spaces": "error",
        "no-whitespace-before-property": "error",
        "object-curly-spacing": ["error", "always"],
        "prefer-object-spread": "warn",
        "prefer-template": "error",
        "quote-props": ["warn", "consistent-as-needed"],
        "quotes": ["error", "double"],
        "semi-spacing": "error",
        "semi-style": "error",
        "semi": "error",
        "space-before-blocks": "warn",
        "space-before-function-paren": ["warn", { anonymous: "never", asyncArrow: "always", named: "never" }],
        "space-in-parens": "warn",
        "space-infix-ops": "warn",
        "space-unary-ops": "warn",
        "spaced-comment": ["warn", "always"],
        "switch-colon-spacing": "warn",
        "template-curly-spacing": "error",
        "template-tag-spacing": "error",
        "yoda": ["warn", "never"]
    }
};
