module.exports = {
    extends: ["./index.js", "plugin:@typescript-eslint/recommended"],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        ecmaVersion: 13,
        sourceType: "module"
    },
    plugins: ["@typescript-eslint"],
    rules: {
        "@typescript-eslint/array-type": "error",
        "@typescript-eslint/await-thenable": "warn",
        "@typescript-eslint/brace-style": ["error", "1tbs"],
        "@typescript-eslint/comma-dangle": ["error", "never"],
        "@typescript-eslint/comma-spacing": "error",
        "@typescript-eslint/consistent-indexed-object-style": "warn",
        "@typescript-eslint/consistent-type-assertions": ["warn", { assertionStyle: "as", objectLiteralTypeAssertions: "allow" }],
        "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
        "@typescript-eslint/consistent-type-exports": "warn",
        // "@typescript-eslint/consistent-type-imports": ["warn", { prefer: "no-type-imports" }],
        "@typescript-eslint/default-param-last": "warn",
        "@typescript-eslint/explicit-member-accessibility": "error",
        "@typescript-eslint/func-call-spacing": "error",
        "@typescript-eslint/indent": ["error", 4],
        "@typescript-eslint/keyword-spacing": "warn",
        "@typescript-eslint/member-delimiter-style": "error",
        "@typescript-eslint/method-signature-style": "warn",
        "@typescript-eslint/no-array-constructor": "error",
        "@typescript-eslint/no-duplicate-imports": "error",
        "@typescript-eslint/no-extra-parens": "warn",
        "@typescript-eslint/no-extra-semi": "warn",
        "@typescript-eslint/object-curly-spacing": ["error", "always"],
        "@typescript-eslint/quotes": ["error", "double"],
        "@typescript-eslint/semi": "error",
        "@typescript-eslint/space-before-function-paren": ["warn", { anonymous: "never", asyncArrow: "always", named: "never" }],
        "@typescript-eslint/space-infix-ops": "warn",
        "brace-style": "off",
        "comma-dangle": "off",
        "comma-spacing": "off",
        "default-param-last": "off",
        "func-call-spacing": "off",
        "indent": "off",
        "keyword-spacing": "off",
        "no-array-constructor": "off",
        "no-duplicate-imports": "off",
        "no-extra-parens": "off",
        "no-extra-semi": "off",
        "no-unused-vars": "off",
        "object-curly-spacing": "off",
        "quotes": "off",
        "semi": "off",
        "space-before-function-paren": "off",
        "space-infix-ops": "off"
        // "@typescript-eslint/explicit-function-return-type": "error",
        // "@typescript-eslint/naming-convention": "warn",
    }
};